apiVersion: v1
kind: Pod
metadata:
  name: nodejs1-example
  labels:
    app: nodejs-1
spec:
  containers:
    - name: nodejs1-example
      image: uresoft/nodejs1-image:1.0
      env:
        - name: PV
          valueFrom:
            configMapKeyRef:
              name: nodejs1-example
              key: pv_path
        - name: NODE_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-credentials
              key: username
        - name: NODE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-credentials
              key: password
      imagePullPolicy: Always
      volumeMounts:
        - name: nodejs1-example-pv
          mountPath: /usr/src/data
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
      ports:
        - containerPort: 3000
  volumes:
    - name: nodejs1-example-pv
      persistentVolumeClaim:
        claimName: pv-volume
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs1-service
  labels:
    app: nodejs-1
spec:
  type: LoadBalancer
  selector:
    app: nodejs-1
  ports:
    - name: http
      port: 80
      targetPort: 3000
